apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: DATA+OMITTED
      server: https://127.0.0.1:54909
    name: desktop
  - cluster:
      certificate-authority-data: DATA+OMITTED
      server: https://127.0.0.1:57053
    name: kind-kind
contexts:
  - context:
      cluster: kind-kind
      user: kind-kind
    name: kind-kind
  - context:
      cluster: desktop
      user: kubernetes-admin
    name: kubernetes-admin@desktop
current-context: kind-kind
kind: Config
preferences: {}
users:
  - name: kind-kind
    user:
      client-certificate-data: DATA+OMITTED
      client-key-data: DATA+OMITTED
  - name: kubernetes-admin
    user:
      client-certificate-data: DATA+OMITTED
      client-key-data: DATA+OMITTED